import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";
import NavBar from "./component/Navbar";

const helvetica = localFont({
  src: "../public/font/HelveticaNeueThin.otf",
});

export const metadata: Metadata = {
  title: "Creasite Next Gen Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={helvetica.className}>
        
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-QW403VZPT6"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-QW403VZPT6');
          `}
        </Script>

        <NavBar />
        {children}
      </body>
    </html>
  );
}